---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose-linux-arm --file stack.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: counter
  name: counter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: counter
    spec:
      containers:
      - image: staranto/simple-http-counter:latest
        name: counter
      - env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 8181
        resources: {}
      restartPolicy: Always
status: {}
...
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose-linux-arm --file stack.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: counter
  name: counter
spec:
  ports:
  - name: "8181"
    port: 8181
    targetPort: 8181
  selector:
    io.kompose.service: counter
status:
  loadBalancer: {}
...
