---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose-linux-arm --file stack.yml convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: pounder
  name: pounder
spec:
  replicas: 4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pounder
    spec:
      containers:
      - env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: staranto/simple-http-pounder:latest
        name: pounder
        resources: {}
      restartPolicy: Always
status: {}
...
